### ISSUE TITLE
24hr Period

### ISSUE THREAD

**Issue by Feehley** [crice009/MMM-NOAATides#3]
First off let me just say this is a phenomenal utility and it's by far the most useful app I have on my MagicMirror. 

My issue is that I want it to have a rotational 24hr period. So I want it to show the past 12 hours and the future 12 hours. 

So if it's almost* midnight, I'd like to be able to see the tides until noon the next day (mostly to prepare for potential flooding). 

Any advice you can give?

* edit

**Comment by crice009** [comment]
Thanks - it was my first foray this deep into the Magic Mirror, and it shows from time to time. 😅

This seems like a solvable problem!
[Here is a commit](https://github.com/crice009/MMM-NOAATides/compare/main...test/further_predictions) that goes after this in the most ham-fisted way possible. I think it should work, but I have not tested it yet. Feel free to give it a try, but I can make no guarantees... 

Hopefully I can come back to this with a more graceful solution sometime in the future. It seems like the main issue would be better tuning the requests to NOAA. It might be nice to have a graph that is always centered on 'now' with the predictions and measured data rolling by very slowly over 24 hours.
